micronaut:
    application:
        name: cozycast-server
    server:
        port: 8080

    router:
        static-resources:
            default:
                enabled: true
                mapping: "/**"
                paths: "classpath:static"
