micronaut:
    application:
        name: cozycast-server
    server:
        port: 80

    router:
        static-resources:
            default:
                enabled: true
                mapping: "/**"
                paths: "classpath:static"
    io:
        watch:
            paths: src/main
            restart: true
