version: '3'

services:
    cozycast-server:
        entrypoint:
        - /root/cozycast/cozycast-server/gradlew
        - run
        - --continuous
        environment:
            SOURCE_URL: $SOURCE_URL
        volumes:
            - "../cozycast-server/cache/avatar:/var/cozycast/avatar/"
            - "../cozycast-server:/root/cozycast/cozycast-server"
            - "../cozycast-server/cache/.gradle:/root/.gradle/repository"
            - "../cozycast-server/cache/build:/root/cozycast/cozycast-server/build"


# mkdir -p cache/avatar cache/.gradle cache/build
